### ISSUE TITLE
Prototype indexes

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/spool-whitepaper#4]
Add overview of this project

Ref
https://github.com/cryptoeconomicslab/spool-whitepaper/issues/3

**Comment by shogochiai** [comment]
```
Title: Staking Pool Protocol - Trustless security enhancer for robust cryptoeconomic system
Abstract: ...
1. Problem
    1-1. Staking as a Deterrence
    1-2. Cryptoeconomic Recoverability
    1-3. Stake Liquidity

2. Solution
    2-1. Trustless Staking Pool
    2-2. SPOOL - Token as a Interface
    2-3. Staking Duration and Withdrawal Term
    2-4. Swingby Protocol - Dutch Auction and Atomic Swap
    2-5. 

3. Risk, Attack and Mitigation
    3-1. Proxy Staking for Self GOX and Fund Stealing
    3-2. Scoring for Proxyless Staking Protocol and Dapps
    3-3. 

4. Rationale

5. Future Works
    5-1. More Proxy Staking Protocol
    5-2. 

```

**Comment by syuhei176** [comment]
Related works swingby protocol, decred, vest.io, polica.io.

**Comment by syuhei176** [comment]
1-1. What is proof of staking? staking is the deterrence for attacking.
1-2. Cryptoeconomic recoverability is important because.... but it's difficult to get recoverability.
1-3. Stake liquidity is important because... but it's difficult to get liquidity.
1-4. Staking pool's scalability is important because... but it's important to get scalability.
